name: Deploy GitHub Pages
on:
  push:
    branches: [main]
    paths: ['docs/**', 'data/metrics.json']

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    uses: actions/configure-pages@v5
    with:
      static_site_generator: other
